title: "My R Learning Book"
author: "Lulu Shi"
copyright: 2024


repository:
   url : https://github.com/crazzy-rabbit/Rscript-to-anaylise-and-visualize
   branch: main
html:
  baseurl: https://crazzy-rabbit.github.io/Rscript-to-anaylise-and-visualize/
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true


#######################################################################################
sphinx:
  config:
    source_suffix:
      - .ipynb

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""    # A path to the jupyter cache that will be used to store execution artifacts. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout                   : 30    # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp               : false # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
                                    # otherwise the notebook's parent directory will be the cwd.
  allow_errors              : true # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output             : show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'
